ap:
  image:
    repository: ghcr.io/llm-d/async-processor
    tag: v0.0.1
  imagePullPolicy: Never

  metrics:
    enabled: true
    port: 9090
    secure: false

  redis:
     port: 6379
     host: "redis-master.redis.svc.cluster.local"
     inferenceGateway: "http://infra-sim-inference-gateway-istio.llm-d-sim.svc.cluster.local:80/v1/completions"
  


