apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "async-processor.fullname" . }}-pod-reader
  namespace: {{ .Values.ap.podWatcher.namespace }}
  labels:
    {{- include "async-processor.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "async-processor.fullname" . }}-pod-reader
  namespace: {{ .Values.ap.podWatcher.namespace }}
  labels:
    {{- include "async-processor.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "async-processor.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "async-processor.fullname" . }}-pod-reader
  apiGroup: rbac.authorization.k8s.io
